# version: "3.8"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: miguel/senna-connect-backend:1.0
#     # command: node start:dev
#     volumes:
#       - .:/app/
#       - /app/node_modules
#     container_name: api-app
#     ports:
#       - ${PORT}:${PORT}
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#       DATABASE_URL: ${DATABASE_URL}
#   postgres:
#     image: postgres:16
#     restart: always
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./postgres:/var/lib/postgresql/data

version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URL: ${DATABASE_URL}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
